### ISSUE TITLE
Consistent key names in dashboard.json

### ISSUE THREAD

**Issue by erikadeal** [pocdata/pocr#1]
Each dashboard should have an object called "highlights." Currently, two of them have "highlights" and two have "highlight."

Unrelated, but could you also change the top-level objects to be
- dash1
- dash2
- dash3
- dash4

Instead of ia, ooh, etc. After thinking about it, this will be more flexible because it will let us switch out the data in the tabs more easily.

**Comment by erikadeal** [comment]
Additionally, `dash3` (`los`) has a typo--it should be "highlights" instead of "hihglights"

**Comment by oieeri26** [comment]
Removed ia, ooh... labels, changed to dash1, dash2...
Corrected highlight type
