### ISSUE TITLE
Duplicate dashboard data

### ISSUE THREAD

**Issue by erikadeal** [pocdata/pocr#2]
The first two objects in the JSON file are both "Investigations and Assessments"; it looks like the OOH data is missing.

Could you add the script to `pocr` so that I/others can take a look and help debug?

**Comment by oieeri26** [comment]
I have been using a branch on rstudio, not sure why it's not visible to anyone but I'll look at it before I leave today.

**Comment by erikadeal** [comment]
You may need to publish it? Local branches don't show up for everyone else unless you explicitly push them to GitHub.

**Comment by oieeri26** [comment]
OOH data restored
Commit script to github pocr under branch landing-dashboard
