### ISSUE TITLE
Wrong dashboard visualization type

### ISSUE THREAD

**Issue by erikadeal** [pocdata/pocr#3]
In I&A, 'Why are households invesitgated?' has a typo and should be type 'bar.'

Sorry, I should have caught these earlier, but I wasn't evaluating the JSON against the original mockup.

**Comment by erikadeal** [comment]
Also, the lines of statistics ('How long do children stay in care?') should have a type. Type 'stat' would be fine.

**Comment by erikadeal** [comment]
Ok, I should have caught this. We don't need a "type" at the top/dashboard level. Two of them are type "highlight" and two are empty; you can just take it out.

**Comment by oieeri26** [comment]
Changed invesitgated to investigated and added type 'bar'
Added type 'stat'
Got rid of top level type
