### ISSUE TITLE
Add "years old" after age ranges in OOH age donut chart

### ISSUE THREAD

**Issue by erikadeal** [pocdata/pocr#7]
The ages look really bare and are not obvious as such without the extra labels.

So instead of 
- 4-9
- 10-14

Make it
- 4-9 years old
- 10-14 years old

This isn't urgent because I can fix it locally; just a request to update the script before the next time you run it.

**Comment by oieeri26** [comment]
Sorry for the delay, this has been updated. The function [get_site_dashboard_data](https://github.com/pocdata/pocr/blob/landing-dashboard/R/get_site_dashboard_data.R) has been updated to the most recent version, but is still a work in progress.
